/* KEPAD ROWS PINS Config*/
#define KEYPAD_R0_PORT	'B'
#define KEYPAD_R0_PIN 	 7
	
#define KEYPAD_R1_PORT	'B'
#define KEYPAD_R1_PIN 	 6
	
#define KEYPAD_R2_PORT	'B'
#define KEYPAD_R2_PIN 	 5
	
#define KEYPAD_R3_PORT	'B'
#define KEYPAD_R3_PIN 	 4

/* KEPAD COLUMNS PINS Config*/
#define KEYPAD_C0_PORT	'B'
#define KEYPAD_C0_PIN    3
			   
#define KEYPAD_C1_PORT	'B'
#define KEYPAD_C1_PIN    2
			   
#define KEYPAD_C2_PORT	'B'
#define KEYPAD_C2_PIN    1
			   
#define KEYPAD_C3_PORT	'B'
#define KEYPAD_C3_PIN    0

/*Maximum Rows and columns*/
#define KEYPAD_ROWSMAXNUM 4
#define KEYPAD_COLSMAXNUM 4

/*kEYPAD PORTS ARRAY*/
#define KEYPAD_ROWS_PORTS	{KEYPAD_R0_PORT,KEYPAD_R1_PORT,KEYPAD_R2_PORT,KEYPAD_R3_PORT}
#define KEYPAD_COLS_PORTS	{KEYPAD_C0_PORT,KEYPAD_C1_PORT,KEYPAD_C2_PORT,KEYPAD_C3_PORT}

/*kEYPAD PINS ARRAY*/
#define KEYPAD_ROWS_PINS	{KEYPAD_R0_PIN ,KEYPAD_R1_PIN ,KEYPAD_R2_PIN ,KEYPAD_R3_PIN }
#define KEYPAD_COLS_PINS	{KEYPAD_C0_PIN ,KEYPAD_C1_PIN ,KEYPAD_C2_PIN ,KEYPAD_C3_PIN }

/*DEFINE KEPAD KEYS*/
#define	KEYPAD_KEYS			{{1,2,3,'f1'},{4,5,6,'f2'},{7,8,9,'f3'},{'*',0,'#','f4'}}

#define KEYPAD_NOKEYPRESS 	225

